environment:

  matrix:
    - TARGET_ARCH: x86
      PYTHON_VERSION: 2.7
      CONDA_INSTALL_LOCN: C:\\Miniconda
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x64
      PYTHON_VERSION: 2.7
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      BUILD_TYPE: MSYS

    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35
      BUILD_TYPE: MSVC

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
      BUILD_TYPE: MSVC

    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36
      BUILD_TYPE: MSVC

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      BUILD_TYPE: MSVC

platform:
    - x64

install:
    # Activate `conda`
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    # Configure conda
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --set always_yes yes --set changeps1 no

    # Create conda environment
    - cmd: if [%BUILD_TYPE%] == [MSVC] conda create -n test python=%PYTHON_VERSION% mpir mpfr mpc
    - cmd: if [%BUILD_TYPE%] == [MSYS] conda create -n test python=%PYTHON_VERSION% libpython m2w64-gmp m2w64-mpfr m2w64-mpc m2w64-toolchain

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: call activate test
    - cmd: if [%BUILD_TYPE%] == [MSVC] python setup.py build_ext --shared=%CONDA_PREFIX%\Library --mpir -DNDEBUG install
    - cmd: if [%BUILD_TYPE%] == [MSYS] python setup.py build_ext --static=%CONDA_PREFIX%\Library\mingw-w64 --msys2 -DNDEBUG install
    - cmd: cd test && python runtests.py && cd ..
