environment:

  matrix:
    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.5
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

    - TARGET_ARCH: x86
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36

    - TARGET_ARCH: x64
      PYTHON_VERSION: 3.6
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
    - x64

install:
    # Activate `conda`
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    # Configure conda
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --set always_yes yes --set changeps1 no

    # Create conda environment
    - cmd: conda create -n msvc_test python=%PYTHON_VERSION% mpir mpfr mpc
    - cmd: conda create -n msys_test python=%PYTHON_VERSION% libpython m2w64-gmp m2w64-mpfr m2w64-mpc m2w64-toolchain

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: echo "Testing MSYS build"
    - cmd: call activate msys_test
    - cmd: python setup.py install --static=%CONDA_PREFIX%\Library\mingw-w64 --msys2
    - cmd: cd test && python runtests.py && cd ..

    - cmd: echo "Testing MSVC build"
    - cmd: call activate msvc_test
    - cmd: python setup.py install --shared=%CONDA_PREFIX%\Library --mpir
    - cmd: cd test && python runtests.py && cd ..
